version: '2'

services:

  mysql:
    image: mysql:latest
    container_name: cqrs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "letmein"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
      MYSQL_DATABASE: "cqrs"
    ports:
      - 3306:3306
#    volumes:
#      - mysql_data:/var/lib/mysql
    restart: always
    networks:
     - cqrs_net

  vehicle:
    depends_on:
      - mysql
    image: cqrs/vehicle:@project.version@
    container_name: cqrs-vehicle
    # change to default for in memory only version
    environment:
      SPRING_PROFILES_ACTIVE: "mysql"
    ports:
      - 8080:8080
    links:
      - mysql:mysql
    networks:
      - cqrs_net

networks:
  cqrs_net:
    driver: bridge